---
- name: Upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  tags: pkg

- name: Install packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - build-essential
      - ca-certificates
      - curl
      - fail2ban
      - git
      - gnupg
      - htop
      - ntp
      - ufw
      - unattended-upgrades
      - vim
    state: latest
    update_cache: true
    autoremove: true
    autoclean: true
  notify:
    - start ntp
    - start fail2ban
  tags: pkg
